# Generated by Django 4.2.17 on 2025-01-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_color_productimage_productitem_productvariation_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_check',
            field=models.BooleanField(default=True, verbose_name='Size check'),
        ),
    ]
