# Generated by Django 4.2.17 on 2024-12-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_sizes_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizes',
            options={'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.AlterModelTable(
            name='sizes',
            table='size',
        ),
    ]
