# Generated by Django 4.2.17 on 2025-01-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_rename_product_name_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name': 'Product Item', 'verbose_name_plural': 'Product Items'},
        ),
    ]
