# Generated by Django 4.2.17 on 2025-01-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_size_size_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='size_check',
        ),
    ]
