# Generated by Django 4.2.17 on 2024-12-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_products_category_subcategories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='categories',
        ),
        migrations.AddField(
            model_name='subcategories',
            name='categories',
            field=models.ManyToManyField(related_name='sub_categories', to='goods.categories', verbose_name='Sub Category'),
        ),
    ]
