# Generated by Django 4.2.17 on 2025-01-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_alter_productitem_options_remove_product_sku_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ['id'], 'verbose_name': 'Product Item', 'verbose_name_plural': 'Product Items'},
        ),

        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL'),
        ),
    ]
