# Generated by Django 4.2.17 on 2024-12-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_remove_subcategories_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='goods.categories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.ManyToManyField(related_name='products', to='goods.sizes', verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='goods.subcategories', verbose_name='SubCategory'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='categories',
            field=models.ManyToManyField(related_name='sub_categories', to='goods.categories', verbose_name='Category'),
        ),
    ]
