# Generated by Django 4.2.17 on 2025-01-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_productitem_options_remove_product_sku_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='sku_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
