# Generated by Django 4.2.17 on 2024-12-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_pantssize_shirtsize_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
    ]
