# Generated by Django 4.2.17 on 2024-12-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_products_category_alter_products_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['subcategory__name', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='subcategories',
            options={'ordering': ['name'], 'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
    ]
