# Generated by Django 4.2.17 on 2025-02-01 11:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_remove_product_sku_id_alter_productitem_sku_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku_id',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='product_images/default.jpg', upload_to=goods.models.image_for_upload, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Product item image'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_item_col', to='goods.color'),
        ),
    ]
