# Generated by Django 4.2.17 on 2024-12-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='pants_size',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='size_type',
        ),
        migrations.AlterField(
            model_name='productsize',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3, null=True, verbose_name='Shirt Size'),
        ),
        migrations.DeleteModel(
            name='PantsSize',
        ),
        migrations.DeleteModel(
            name='ShirtSize',
        ),
    ]
