# Generated by Django 4.2.17 on 2024-12-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_remove_productsize_pants_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
    ]
