# Generated by Django 4.2.17 on 2025-01-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_alter_category_slug_alter_category_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sdu_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='SDU ID'),
        ),
    ]
