# Generated by Django 4.2.17 on 2025-01-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_product_sdu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sdu_id',
        ),
        migrations.AddField(
            model_name='product',
            name='sku_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='SKU'),
        ),
    ]
