# Generated by Django 4.2.17 on 2025-01-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_remove_product_sdu_id_product_sku_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
    ]
