# Generated by Django 4.2.17 on 2025-01-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_remove_category_unique_slug_for_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Color name')),
                ('hex_code', models.CharField(help_text='Example: #FFFFFF', max_length=7, unique=True, verbose_name='Hex code')),
            ],
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Main image'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='goods.color', verbose_name='Colors'),
        ),
    ]
