# Generated by Django 4.2.17 on 2025-01-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_remove_product_is_active_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', max_length=200, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
